# Generated by Django 4.0.2 on 2023-02-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aprobada',
            old_name='materia',
            new_name='materia_ap',
        ),
        migrations.RenameField(
            model_name='aprobada',
            old_name='alumno',
            new_name='matricula_alumno',
        ),
        migrations.AlterField(
            model_name='aprobada',
            name='id_aprobada',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
