# Generated by Django 4.0.2 on 2022-11-22 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tiempo',
            name='fecha_final',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de finalización'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tiempo',
            name='fecha_inicio',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de inicio'),
        ),
    ]
