# Generated by Django 4.0.2 on 2023-02-03 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0002_rename_materia_aprobada_materia_ap_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aprobada',
            name='id_aprobada',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
