# Generated by Django 4.0.2 on 2022-12-09 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0004_alter_tiempo_fecha_final_alter_tiempo_fecha_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempo',
            name='fecha_final',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de finalización'),
        ),
        migrations.AlterField(
            model_name='tiempo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de inicio'),
        ),
        migrations.CreateModel(
            name='Aprobada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materias.alumno')),
            ],
        ),
    ]
