# Generated by Django 4.0.2 on 2022-12-11 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materias', '0005_alter_tiempo_fecha_final_alter_tiempo_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Aprobada',
        ),
    ]
